export const FactionList2 = [
  { cat: 'Mics.', name: 'Select Faction...' },
  { cat: 'Imperium', name: 'Ultramarines' },
  { cat: 'Aeldari', name: 'CraftWorlds' },
  { cat: 'Necrons', name: 'Necrons' },
  { cat: 'Orks', name: 'Orks' },
  { cat: 'Tyranids', name: 'Tyranids' },
  { cat: 'Chaos', name: 'Black Legion' },
];

export const FactionList = [
  { cat: 'Aeldari', name: 'Asuryani' },
  { cat: 'Aeldari', name: 'Drukhari' },
  { cat: 'Aeldari', name: 'Harlequins' },
  { cat: 'Aeldari', name: 'Ynnari' },
  { cat: 'Aeldari', name: 'Aeldari' },
  { cat: 'Chaos', name: 'Chaos Knights' },
  { cat: 'Chaos', name: 'Daemons' },
  { cat: 'Chaos', name: 'Death Guard' },
  { cat: 'Chaos', name: 'Fallen' },
  { cat: 'Chaos', name: 'Gellerpox Infected' },
  { cat: 'Chaos', name: 'Heretic Astarties' },
  { cat: 'Chaos', name: 'Servants of the Abyss' },
  { cat: 'Chaos', name: 'Thousand Sons' },
  { cat: 'Chaos', name: 'Titanicus Traitoris' },
  { cat: 'Chaos', name: 'Chaos' },
  { cat: 'Imperium', name: 'Adepta Sororitas' },
  { cat: 'Imperium', name: 'Adeptus Astarties' },
  { cat: 'Imperium', name: 'Adeptus Custodies' },
  { cat: 'Imperium', name: 'Adeptus Mechanicus' },
  { cat: 'Imperium', name: 'Adeptus Titanicus' },
  { cat: 'Imperium', name: 'Astra Militarum' },
  { cat: 'Imperium', name: 'Elucidian Starstriders' },
  { cat: 'Imperium', name: 'Fallen' },
  { cat: 'Imperium', name: 'Grey Knights' },
  { cat: 'Imperium', name: 'Imperial Knights' },
  { cat: 'Imperium', name: 'Inquisition' },
  { cat: 'Imperium', name: 'Officio Assassinorum' },
  { cat: 'Imperium', name: 'Sisters of Silence' },
  { cat: 'Imperium', name: 'Imperium' },
  { cat: 'Necrons', name: 'Necrons' },
  { cat: 'Orks', name: 'Orks' },
  { cat: "T'au Empire", name: "T'au Emplire" },
  { cat: 'Tyranids', name: 'Brood Brothers' },
  { cat: 'Tyranids', name: 'Genestealer Cults' },
  { cat: 'Tyranids', name: 'Tyranids' },
];

export const SecondariesList = [
  { cat: 'Misc.', name: 'Choose one...' },

  { cat: 'optgroup', name: 'Codex Specific Secondaries' },
  { cat: 'Codex', name: 'Codex Specific' },

  { cat: 'optgroup', name: 'Battlefield Supremacy' },
  { cat: 'Battlefield Supremacy', name: 'Engage on All Fronts' },
  { cat: 'Battlefield Supremacy', name: 'Linebreaker' },
  { cat: 'Battlefield Supremacy', name: 'Domination' },

  { cat: 'optgroup', name: 'No Mercy, No Respite' },
  { cat: 'No Mercy, No Respite', name: 'Thin Their Ranks' },
  { cat: 'No Mercy, No Respite', name: 'Grind Them Down' },
  { cat: 'No Mercy, No Respite', name: 'While We Stand, We Fight' },

  { cat: 'optgroup', name: 'Purge the Enemy' },
  { cat: 'Purge the Enemy', name: 'Titan Hunter' },
  { cat: 'Purge the Enemy', name: 'Bring it Down' },
  { cat: 'Purge the Enemy', name: 'Cut Off the Head' },
  { cat: 'Purge the Enemy', name: 'Assassinate' },

  { cat: 'optgroup', name: 'Shadow Operations' },
  { cat: 'Shadow Operations', name: 'Raise the Banners High' },
  { cat: 'Shadow Operations', name: 'Investigate Sights' },
  { cat: 'Shadow Operations', name: 'Deploy Scramblers' },
  { cat: 'Shadow Operations', name: 'Teleport Homer' },

  { cat: 'optgroup', name: 'Warpcraft' },
  { cat: 'Warpcraft', name: 'Abhor the Witch' },
  { cat: 'Warpcraft', name: 'Mental Interrogation' },
  { cat: 'Warpcraft', name: 'Psychic Ritual' },
  { cat: 'Warpcraft', name: 'Pierce the Veil' },
];
